- name: 'Add repo PHP 5.6 (Ondřej Surý PPA)'
  apt_repository: repo='ppa:ondrej/php'

- name: 'PHP + libraries installed'
  apt: pkg={{ item }} state=latest
  with_items:
    - php5.6-cli
    - php5.6-intl
    - php5.6-json
    - php5.6-curl
    - php5.6-mcrypt
    - php5.6-gd
    - php5.6-pgsql
    - php5.6-mysql
    - php5.6-readline
    - php5.6-mbstring
    - php5.6-zip
    - php5.6-xml
    - php-pear
  tags: php

- name: Enable PHP modules
  shell: phpenmod {{ item }}
  with_items:
    - mcrypt
  tags: php

- name: Configure PHP settings
  template: src=php.ini dest=/etc/php/5.6/apache2/conf.d/custom.ini
  tags: php

- name: Chown PHP sessions dir
  file: path=/var/lib/php state=directory owner={{ username }} group={{ username }}
  tags: php