- name: 'Add repo PHP 5.5 (Ondřej Surý PPA)'
  apt_repository: repo='ppa:ondrej/php'

- name: 'PHP + libraries installed'
  apt: pkg={{ item }} state=latest
  with_items:
    - php5.5-cli
    - php5.5-intl
    - php5.5-json
    - php5.5-curl
    - php5.5-mcrypt
    - php5.5-gd
    - php5.5-pgsql
    - php5.5-mysql
    - php5.5-readline
    - php5.5-mbstring
    - php5.5-zip
    - php5.5-xml
    - php-pear
  tags: php

- name: Enable PHP modules
  shell: phpenmod {{ item }}
  with_items:
    - mcrypt
  tags: php

- name: Configure PHP settings
  template: src=php.ini dest=/etc/php/5.5/apache2/conf.d/custom.ini
  tags: php

- name: Chown PHP sessions dir
  file: path=/var/lib/php state=directory owner={{ username }} group={{ username }}
  tags: php