- name: 'Add repo PHP 7.0 (Ondřej Surý PPA)'
  apt_repository: repo='ppa:ondrej/php'

- name: 'PHP + libraries installed'
  apt: pkg={{ item }} state=latest
  with_items:
    - php7.0-cli
    - php7.0-readline
    - php7.0-intl
    - php7.0-json
    - php7.0-curl
    - php7.0-gd
    - php7.0-pgsql
    - php7.0-mysql
    - php7.0-mbstring
    - php7.0-zip
    - php7.0-xml
    - php7.0-mcrypt
  tags: php

- name: Enable PHP modules
  shell: phpenmod {{ item }}
  with_items:
    - mcrypt
  tags: php

- name: Configure PHP settings
  template: src=php.ini dest=/etc/php/7.0/apache2/conf.d/custom.ini
  tags: php

- name: Chown PHP sessions dir
  file: path=/var/lib/php state=directory owner={{ username }} group={{ username }}
  tags: php